Traceback (most recent call last):
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/getaqdata.py", line 117, in connect_and_read
    navigate_to_accuweather_aq_page(accuweather_page)
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/getaqdata.py", line 52, in navigate_to_accuweather_aq_page
    page.goto("https://www.accuweather.com/ro/ro/bucharest/1-287430_18_al/air-quality-index/1-287430_18_al")
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/.venv/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 9002, in goto
    self._sync(
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/.venv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/.venv/lib/python3.11/site-packages/playwright/_impl/_page.py", line 553, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/.venv/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/.venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspberrypi/Documents/projects/air-quality-rpi5/.venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
navigating to "https://www.accuweather.com/ro/ro/bucharest/1-287430_18_al/air-quality-index/1-287430_18_al", waiting until "load"

